### ISSUE TITLE
Review low batery HMI

### ISSUE THREAD

**Issue by cua-cua** [Bulebots/bulebule#176]
When low battery is detected a message is sent and the LED is power on with toggle. 
1) Verify the behaviour above
2) Maybe is better to keep the led blinking and to send the message periodically?

**Comment by Peque** [comment]
A beep could be great too (we can now use the speaker on TIM1! ^^). Not implemented yet, though...

**Comment by Peque** [comment]
Closed by https://github.com/Bulebots/bulebule/pull/326.
