### ISSUE TITLE
ADC2 reconfiguration

### ISSUE THREAD

**Issue by cua-cua** [Bulebots/bulebule#235]
With the absence of gyroscope readings, the configuration of the ADC for battery voltage could be   updated to be for example periodic. 
Analyze and reconfigured if needed the ADC2.

**Comment by Peque** [comment]
Yeah, agree with this. Makes little sense to read the battery so many times. :+1:

**Comment by cua-cua** [comment]
The ADC2 setup and interruption were deleted and also the adc activation on the state machine, but the battery.c is untouched. Reuse it to reimplement get_battery_voltage function.

**Comment by Peque** [comment]
Yeah, we can probably just remove `adc1_2_isr()`, add a new ADC2 setup function and update the `get_battery_voltage()` implementation accordingly. :+1:
