### ISSUE TITLE
Clean from Makefile is not working with mmlib

### ISSUE THREAD

**Issue by cua-cua** [Bulebots/bulebule#398]
`make clean` does not work within the folder mmlib. 
The .d files remain

**Comment by Peque** [comment]
Can't reproduce. :woman_shrugging:

**Comment by Peque** [comment]
Can you try running `setup_libopencm3.sh` again?

Maybe it is due to the latest changes in: https://github.com/libopencm3/libopencm3-examples/commits/master/examples/rules.mk

**Comment by cua-cua** [comment]
With the new rules it works, thank you!
