### ISSUE TITLE
Few function definition are missings

### ISSUE THREAD

**Issue by Embedded-Guru** [Bulebots/bulebule#435]
Is this project repo holds the complete source code?

Could you help me figure whether the functions related to mpu, kinematic_configuration, etc are located?

**Comment by Peque** [comment]
@Embedded-Guru Everything is here, yeah. But note how `mmlib` is added as a submodule under `src/`, so remember to clone the repo recursively. :wink: 

`mmlib` holds code related to the MPU and control.
